# Generated by Django 5.1.4 on 2025-01-29 10:47

import django.db.models.deletion
import game.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='current_view',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.currentview'),
        ),
        migrations.AlterField(
            model_name='gameparticipant',
            name='private_key',
            field=models.CharField(default=game.models.generate_private_key, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='gameparticipant',
            name='round_lock',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gameparticipant',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
