# Generated by Django 5.1.4 on 2025-01-29 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_game_current_view_alter_gameparticipant_private_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jepardycolumn',
            name='questions',
        ),
        migrations.AddField(
            model_name='jepardycolumn',
            name='questions',
            field=models.ManyToManyField(related_name='columns', to='game.jepardyquestion'),
        ),
    ]
