# Generated by Django 5.1.4 on 2025-01-29 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_remove_jepardycolumn_questions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentview',
            name='jepardy_table_id',
        ),
        migrations.AddField(
            model_name='currentview',
            name='jepardy_table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.jepardytable'),
        ),
        migrations.AlterField(
            model_name='currentview',
            name='question_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.gamequestion'),
        ),
    ]
