# Generated by Django 5.1.4 on 2025-02-03 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_game_moderator_key_game_spectator_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='buzzers_locked',
            field=models.BooleanField(default=True),
        ),
    ]
