# Generated by Django 5.1.4 on 2025-02-03 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_game_buzz_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='buzz_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buzz_games', to='game.gameparticipant'),
        ),
    ]
