# Generated by Django 5.1.4 on 2025-02-03 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_alter_game_buzz_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='buzz_player',
        ),
        migrations.AddField(
            model_name='game',
            name='buzz_player_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
