# Generated by Django 5.1.4 on 2025-02-06 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_remove_game_buzz_player_game_buzz_player_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentview',
            name='answer_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='currentview',
            name='question_visible',
            field=models.BooleanField(default=False),
        ),
    ]
