# Generated by Django 5.1.4 on 2025-02-09 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_currentview_answer_visible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentview',
            name='timer',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='currentview',
            name='timer_break',
            field=models.BooleanField(default=False),
        ),
    ]
