# Generated by Django 5.1.4 on 2025-02-09 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_currentview_timer_currentview_timer_break'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentview',
            name='timer',
        ),
        migrations.RemoveField(
            model_name='currentview',
            name='timer_break',
        ),
    ]
